import { Composer } from "grammy";
import type { Ctx } from "../bot.js";
import { defaultSubscriptionDays, LibraryUnavailableError, readLibrary, updateLibrary, userId } from "../library-data.js";
import { now } from "../library-clock.js";
import { adminChatIds, inlineButton, inlineKeyboard, requireOwner } from "../toolkit/index.js";

type AdminSession = Ctx["session"] & { adminStep?: "menu_add" | "menu_rename" | "file_upload" | "file_edit" | "coupon_add" | "broadcast"; selectedId?: string };
const composer = new Composer<Ctx>();
const mainKeyboard = () => inlineKeyboard([
  [inlineButton("Menus", "admin:menus"), inlineButton("Files", "admin:files")],
  [inlineButton("Purchases", "admin:purchases"), inlineButton("Coupons", "admin:coupons")],
  [inlineButton("Broadcast", "admin:broadcast"), inlineButton("Analytics", "admin:analytics")],
  [inlineButton("← Main menu", "menu:main")],
]);
async function guard(ctx: Ctx): Promise<boolean> { return requireOwner(ctx); }
async function panel(ctx: Ctx, edit: boolean): Promise<void> {
  const text = "Manage your library, payments, and audience.";
  if (edit) await ctx.editMessageText(text, { reply_markup: mainKeyboard() }); else await ctx.reply(text, { reply_markup: mainKeyboard() });
}

composer.command("admin", async (ctx) => { if (!(await guard(ctx))) return; await panel(ctx, false); });
composer.callbackQuery("admin:home", async (ctx) => { await ctx.answerCallbackQuery(); if (!(await guard(ctx))) return; await panel(ctx, true); });

composer.callbackQuery("admin:menus", async (ctx) => {
  await ctx.answerCallbackQuery(); if (!(await guard(ctx))) return;
  try { const state = await readLibrary(ctx); const rows = state.menuIds.filter((id) => id !== "root").map((id) => [inlineButton(`${state.menus[id].emoji} ${state.menus[id].title}`, `admin:menu:${id}`)]); await ctx.editMessageText(rows.length ? "Choose a menu to manage." : "No custom menus yet — tap Add menu to create one.", { reply_markup: inlineKeyboard([...rows, [inlineButton("Add menu", "admin:menuadd")], [inlineButton("← Admin", "admin:home")]]) }); } catch { await ctx.editMessageText("The library is getting ready. Please try again shortly."); }
});
composer.callbackQuery("admin:menuadd", async (ctx) => { await ctx.answerCallbackQuery(); if (!(await guard(ctx))) return; (ctx.session as AdminSession).adminStep = "menu_add"; await ctx.editMessageText("Send the menu as: title | emoji | description\nIt will be added to the Library home.", { reply_markup: inlineKeyboard([[inlineButton("Cancel", "admin:menus")]]) }); });
composer.callbackQuery(/^admin:menu:(.+)$/, async (ctx) => {
  await ctx.answerCallbackQuery(); if (!(await guard(ctx))) return; const id = String(ctx.match[1]);
  try { const state = await readLibrary(ctx); const menu = state.menus[id]; if (!menu) { await ctx.editMessageText("That menu no longer exists."); return; } await ctx.editMessageText(`${menu.emoji} ${menu.title}\n${menu.description || "No description provided."}`, { reply_markup: inlineKeyboard([[inlineButton("Rename", `admin:menurename:${id}`), inlineButton("Move up", `admin:menuup:${id}`)], [inlineButton(menu.visible ? "Hide" : "Show", `admin:menuvisible:${id}`), inlineButton("Delete", `admin:menudelete:${id}`)], [inlineButton("← Menus", "admin:menus")]]) }); } catch { await ctx.editMessageText("Couldn't open that menu. Please try again."); }
});
composer.callbackQuery(/^admin:menurename:(.+)$/, async (ctx) => { await ctx.answerCallbackQuery(); if (!(await guard(ctx))) return; (ctx.session as AdminSession).adminStep = "menu_rename"; (ctx.session as AdminSession).selectedId = String(ctx.match[1]); await ctx.editMessageText("Send the new title, emoji, and description as: title | emoji | description"); });
composer.callbackQuery(/^admin:menuup:(.+)$/, async (ctx) => { await ctx.answerCallbackQuery(); if (!(await guard(ctx))) return; const id = String(ctx.match[1]); try { await updateLibrary(ctx, (state) => { const menu = state.menus[id]; if (!menu) return; const siblings = state.menuIds.map((key) => state.menus[key]).filter((item) => item && item.parentId === menu.parentId).sort((a, b) => a.order - b.order); const at = siblings.findIndex((item) => item.id === id); if (at > 0) { const above = siblings[at - 1]; [menu.order, above.order] = [above.order, menu.order]; } }); await ctx.answerCallbackQuery({ text: "Menu order updated." }); await ctx.editMessageText("Menu order updated.", { reply_markup: inlineKeyboard([[inlineButton("← Menus", "admin:menus")]]) }); } catch { await ctx.editMessageText("Couldn't reorder that menu. Please try again."); } });
composer.callbackQuery(/^admin:menuvisible:(.+)$/, async (ctx) => { await ctx.answerCallbackQuery(); if (!(await guard(ctx))) return; const id = String(ctx.match[1]); try { await updateLibrary(ctx, (state) => { if (state.menus[id]) state.menus[id].visible = !state.menus[id].visible; }); await ctx.editMessageText("Menu visibility updated.", { reply_markup: inlineKeyboard([[inlineButton("← Menus", "admin:menus")]]) }); } catch { await ctx.editMessageText("Couldn't update that menu. Please try again."); } });
composer.callbackQuery(/^admin:menudelete:(.+)$/, async (ctx) => { await ctx.answerCallbackQuery(); if (!(await guard(ctx))) return; const id = String(ctx.match[1]); try { const result = await updateLibrary(ctx, (state) => { if (state.menuIds.some((key) => state.menus[key]?.parentId === id) || state.fileIds.some((key) => state.files[key]?.attachedMenus.includes(id))) return false; delete state.menus[id]; state.menuIds = state.menuIds.filter((key) => key !== id); return true; }); await ctx.editMessageText(result ? "Menu deleted." : "Move its files and sub-menus before deleting this menu.", { reply_markup: inlineKeyboard([[inlineButton("← Menus", "admin:menus")]]) }); } catch { await ctx.editMessageText("Couldn't delete that menu. Please try again."); } });

composer.callbackQuery("admin:files", async (ctx) => { await ctx.answerCallbackQuery(); if (!(await guard(ctx))) return; try { const state = await readLibrary(ctx); const rows = state.fileIds.map((id) => [inlineButton(state.files[id].title, `admin:file:${id}`)]); await ctx.editMessageText(rows.length ? "Choose a file to manage." : "No files yet — tap Upload file to add one.", { reply_markup: inlineKeyboard([...rows.slice(0, 20), [inlineButton("Upload file", "admin:fileupload")], [inlineButton("← Admin", "admin:home")]]) }); } catch { await ctx.editMessageText("The library is getting ready. Please try again shortly."); } });
composer.callbackQuery("admin:fileupload", async (ctx) => { await ctx.answerCallbackQuery(); if (!(await guard(ctx))) return; (ctx.session as AdminSession).adminStep = "file_upload"; await ctx.editMessageText("Send the file with a caption: title | description | duration in seconds\nDuration is optional.", { reply_markup: inlineKeyboard([[inlineButton("Cancel", "admin:files")]]) }); });
composer.callbackQuery(/^admin:file:(.+)$/, async (ctx) => { await ctx.answerCallbackQuery(); if (!(await guard(ctx))) return; const id = String(ctx.match[1]); try { const state = await readLibrary(ctx); const file = state.files[id]; if (!file) { await ctx.editMessageText("That file no longer exists."); return; } await ctx.editMessageText(`${file.title}\n${file.description || "No description provided."}`, { reply_markup: inlineKeyboard([[inlineButton("Edit", `admin:fileedit:${id}`), inlineButton("Move", `admin:filemove:${id}`)], [inlineButton(file.pinned ? "Unpin" : "Pin", `admin:filepin:${id}`), inlineButton("Delete", `admin:filedelete:${id}`)], [inlineButton("← Files", "admin:files")]]) }); } catch { await ctx.editMessageText("Couldn't open that file. Please try again."); } });
composer.callbackQuery(/^admin:fileedit:(.+)$/, async (ctx) => { await ctx.answerCallbackQuery(); if (!(await guard(ctx))) return; (ctx.session as AdminSession).adminStep = "file_edit"; (ctx.session as AdminSession).selectedId = String(ctx.match[1]); await ctx.editMessageText("Send the new title, description, and duration as: title | description | duration\nLeave duration blank to keep it unchanged."); });
composer.callbackQuery(/^admin:filemove:(.+)$/, async (ctx) => { await ctx.answerCallbackQuery(); if (!(await guard(ctx))) return; const fileId = String(ctx.match[1]); try { const state = await readLibrary(ctx); const rows = state.menuIds.map((id) => [inlineButton(`${state.menus[id].emoji} ${state.menus[id].title}`, `admin:filetomenu:${fileId}:${id}`)]); await ctx.editMessageText("Choose the file's new menu.", { reply_markup: inlineKeyboard([...rows, [inlineButton("Cancel", `admin:file:${fileId}`)]]) }); } catch { await ctx.editMessageText("Couldn't load menus. Please try again."); } });
composer.callbackQuery(/^admin:filetomenu:([^:]+):([^:]+)$/, async (ctx) => { await ctx.answerCallbackQuery(); if (!(await guard(ctx))) return; try { const [, fileId, menuId] = ctx.match; await updateLibrary(ctx, (state) => { if (state.files[fileId] && state.menus[menuId]) state.files[fileId].attachedMenus = [menuId]; }); await ctx.editMessageText("File moved.", { reply_markup: inlineKeyboard([[inlineButton("← Files", "admin:files")]]) }); } catch { await ctx.editMessageText("Couldn't move that file. Please try again."); } });
composer.callbackQuery(/^admin:filepin:(.+)$/, async (ctx) => { await ctx.answerCallbackQuery(); if (!(await guard(ctx))) return; try { const id = String(ctx.match[1]); await updateLibrary(ctx, (state) => { if (state.files[id]) state.files[id].pinned = !state.files[id].pinned; }); await ctx.editMessageText("File pin updated.", { reply_markup: inlineKeyboard([[inlineButton("← Files", "admin:files")]]) }); } catch { await ctx.editMessageText("Couldn't update that file. Please try again."); } });
composer.callbackQuery(/^admin:filedelete:(.+)$/, async (ctx) => { await ctx.answerCallbackQuery(); if (!(await guard(ctx))) return; try { const id = String(ctx.match[1]); await updateLibrary(ctx, (state) => { delete state.files[id]; state.fileIds = state.fileIds.filter((key) => key !== id); state.userIds.forEach((key) => { state.users[key].favorites = state.users[key].favorites.filter((favorite) => favorite !== id); }); }); await ctx.editMessageText("File deleted.", { reply_markup: inlineKeyboard([[inlineButton("← Files", "admin:files")]]) }); } catch { await ctx.editMessageText("Couldn't delete that file. Please try again."); } });

composer.callbackQuery("admin:purchases", async (ctx) => { await ctx.answerCallbackQuery(); if (!(await guard(ctx))) return; try { const state = await readLibrary(ctx); const waiting = state.purchaseIds.map((id) => state.purchases[id]).filter((purchase) => purchase.status === "awaiting_proof"); await ctx.editMessageText(waiting.length ? "Payment proofs waiting for review." : "No payment proofs are waiting.", { reply_markup: inlineKeyboard([...waiting.map((purchase) => [inlineButton("Review payment", `admin:purchase:${purchase.id}`)]), [inlineButton("← Admin", "admin:home")]]) }); } catch { await ctx.editMessageText("Couldn't load purchases. Please try again."); } });
composer.callbackQuery(/^admin:purchase:(.+)$/, async (ctx) => { await ctx.answerCallbackQuery(); if (!(await guard(ctx))) return; const id = String(ctx.match[1]); try { const purchase = (await readLibrary(ctx)).purchases[id]; if (!purchase || purchase.status !== "awaiting_proof") { await ctx.editMessageText("That payment was already handled."); return; } if (purchase.proofFileId) { try { if (purchase.proofKind === "photo") await ctx.replyWithPhoto(purchase.proofFileId, { caption: "Payment proof" }); else await ctx.replyWithDocument(purchase.proofFileId, { caption: "Payment proof" }); } catch { await ctx.reply("The proof file is no longer available, but you can still record your decision."); } } await ctx.editMessageText("Review this payment proof.", { reply_markup: inlineKeyboard([[inlineButton("Mark paid", `admin:paid:${id}`), inlineButton("Reject", `admin:reject:${id}`)], [inlineButton("← Purchases", "admin:purchases")]]) }); } catch { await ctx.editMessageText("Couldn't open that payment. Please try again."); } });
composer.callbackQuery(/^admin:paid:(.+)$/, async (ctx) => { await ctx.answerCallbackQuery(); if (!(await guard(ctx))) return; const days = defaultSubscriptionDays(ctx); if (!days) { await ctx.editMessageText("Default subscription duration isn't set up yet."); return; } try { const id = String(ctx.match[1]); const purchase = await updateLibrary(ctx, (state) => { const item = state.purchases[id]; if (!item || item.status !== "awaiting_proof") return undefined; const start = now(); item.status = "paid"; item.startDate = start.toISOString(); item.endDate = new Date(start.getTime() + days * 86_400_000).toISOString(); return item; }); if (!purchase) { await ctx.editMessageText("That payment was already handled."); return; } try { await ctx.api.sendMessage(purchase.user, "Your payment is confirmed. Your premium access is active."); } catch { /* Users may block the bot after submitting proof. */ } await ctx.editMessageText("Payment marked paid and access granted.", { reply_markup: inlineKeyboard([[inlineButton("← Purchases", "admin:purchases")]]) }); } catch { await ctx.editMessageText("Couldn't mark that payment paid. Please try again."); } });
composer.callbackQuery(/^admin:reject:(.+)$/, async (ctx) => { await ctx.answerCallbackQuery(); if (!(await guard(ctx))) return; try { const id = String(ctx.match[1]); await updateLibrary(ctx, (state) => { if (state.purchases[id]) state.purchases[id].status = "rejected"; }); await ctx.editMessageText("Payment rejected.", { reply_markup: inlineKeyboard([[inlineButton("← Purchases", "admin:purchases")]]) }); } catch { await ctx.editMessageText("Couldn't reject that payment. Please try again."); } });

composer.callbackQuery("admin:coupons", async (ctx) => { await ctx.answerCallbackQuery(); if (!(await guard(ctx))) return; try { const state = await readLibrary(ctx); await ctx.editMessageText(state.couponCodes.length ? `${state.couponCodes.length} coupon${state.couponCodes.length === 1 ? "" : "s"} available.` : "No coupons yet — tap Create coupon to add one.", { reply_markup: inlineKeyboard([[inlineButton("Create coupon", "admin:couponadd")], [inlineButton("← Admin", "admin:home")]]) }); } catch { await ctx.editMessageText("Couldn't load coupons. Please try again."); } });
composer.callbackQuery("admin:couponadd", async (ctx) => { await ctx.answerCallbackQuery(); if (!(await guard(ctx))) return; (ctx.session as AdminSession).adminStep = "coupon_add"; await ctx.editMessageText("Send the coupon as: code | discount percent | access days | usage limit"); });
composer.callbackQuery("admin:broadcast", async (ctx) => { await ctx.answerCallbackQuery(); if (!(await guard(ctx))) return; (ctx.session as AdminSession).adminStep = "broadcast"; await ctx.editMessageText("Send the message you want to broadcast to everyone who has used the bot."); });
composer.callbackQuery("admin:analytics", async (ctx) => { await ctx.answerCallbackQuery(); if (!(await guard(ctx))) return; try { const state = await readLibrary(ctx); const paid = state.purchaseIds.filter((id) => state.purchases[id].status === "paid").length; await ctx.editMessageText(`Library report\nUsers: ${state.userIds.length}\nFiles: ${state.fileIds.length}\nFile views: ${state.analytics.fileViews}\nDownloads: ${state.analytics.fileDownloads}\nPaid subscriptions: ${paid}`, { reply_markup: inlineKeyboard([[inlineButton("Export report", "admin:export")], [inlineButton("← Admin", "admin:home")]]) }); } catch { await ctx.editMessageText("Couldn't load analytics. Please try again."); } });
composer.callbackQuery("admin:export", async (ctx) => { await ctx.answerCallbackQuery(); if (!(await guard(ctx))) return; try { const state = await readLibrary(ctx); await ctx.reply(`Library report\nUsers: ${state.userIds.length}\nFiles: ${state.fileIds.length}\nMenu activity: ${state.analytics.menuActivity}\nFile views: ${state.analytics.fileViews}\nDownloads: ${state.analytics.fileDownloads}`); } catch { await ctx.reply("Couldn't export the report. Please try again."); } });

composer.on(["message:document", "message:audio", "message:video"], async (ctx, next) => {
  if ((ctx.session as AdminSession).adminStep !== "file_upload") return next();
  const media = ctx.message.document ?? ctx.message.audio ?? ctx.message.video;
  if (!media) return next();
  const [titleRaw, descriptionRaw = "", durationRaw = ""] = (ctx.message.caption ?? "").split("|").map((part) => part.trim());
  if (!titleRaw) { await ctx.reply("Add a caption with the file title, then send it again."); return; }
  try { await updateLibrary(ctx, (state) => { const id = `file_${state.fileIds.length + 1}_${now().getTime()}`; const typed = media as { mime_type?: string; file_size?: number; duration?: number; file_id: string }; state.files[id] = { id, title: titleRaw.slice(0, 120), description: descriptionRaw.slice(0, 500), type: typed.mime_type ?? "file", size: typed.file_size ?? 0, duration: Number(durationRaw) > 0 ? Number(durationRaw) : typed.duration, pinned: false, telegramFileId: typed.file_id, attachedMenus: ["root"], createdAt: now().toISOString(), updatedAt: now().toISOString() }; state.fileIds.push(id); }); (ctx.session as AdminSession).adminStep = undefined; await ctx.reply("File added to the Library home."); } catch { await ctx.reply("Couldn't save that file. Please send it again."); }
});
composer.on("message:text", async (ctx, next) => {
  const session = ctx.session as AdminSession; const step = session.adminStep; if (!step) return next();
  const text = ctx.message.text.trim();
  try {
    if (step === "menu_add" || step === "menu_rename") { const [title, emoji = "📁", description = ""] = text.split("|").map((part) => part.trim()); if (!title) { await ctx.reply("Add a menu title, then try again."); return; } await updateLibrary(ctx, (state) => { if (step === "menu_add") { const id = `menu_${state.menuIds.length + 1}_${now().getTime()}`; state.menus[id] = { id, title: title.slice(0, 80), emoji: emoji.slice(0, 8) || "📁", description: description.slice(0, 240), parentId: "root", order: state.menuIds.length, visible: true, pinned: false }; state.menuIds.push(id); } else if (session.selectedId && state.menus[session.selectedId]) Object.assign(state.menus[session.selectedId], { title: title.slice(0, 80), emoji: emoji.slice(0, 8) || "📁", description: description.slice(0, 240) }); }); session.adminStep = undefined; await ctx.reply(step === "menu_add" ? "Menu created." : "Menu updated."); return; }
    if (step === "file_edit") { const [title, description = "", duration = ""] = text.split("|").map((part) => part.trim()); if (!title || !session.selectedId) { await ctx.reply("Add a file title, then try again."); return; } await updateLibrary(ctx, (state) => { const file = state.files[session.selectedId!]; if (file) { file.title = title.slice(0, 120); file.description = description.slice(0, 500); if (duration) file.duration = Number(duration) || file.duration; file.updatedAt = now().toISOString(); } }); session.adminStep = undefined; await ctx.reply("File updated."); return; }
    if (step === "coupon_add") { const [rawCode, discountRaw, durationRaw, limitRaw] = text.split("|").map((part) => part.trim()); const code = rawCode?.toUpperCase(); const discount = Number(discountRaw); const duration = Number(durationRaw); const limit = Number(limitRaw); if (!code || !/^[A-Z0-9_-]{3,32}$/.test(code) || !Number.isFinite(discount) || discount < 0 || discount > 100 || !Number.isInteger(duration) || duration < 1 || !Number.isInteger(limit) || limit < 1) { await ctx.reply("Use a code, discount from 0 to 100, whole access days, and a whole usage limit."); return; } const created = await updateLibrary(ctx, (state) => { if (state.coupons[code]) return false; state.coupons[code] = { code, discount, duration, usageLimit: limit, usedBy: [], createdBy: userId(ctx), createdAt: now().toISOString() }; state.couponCodes.push(code); return true; }); if (!created) { await ctx.reply("That coupon code already exists. Choose another one."); return; } session.adminStep = undefined; await ctx.reply("Coupon created."); return; }
    if (step === "broadcast") { const state = await readLibrary(ctx); let sent = 0; for (const recipient of state.userIds) { try { await ctx.api.sendMessage(recipient, text.slice(0, 4096)); sent++; } catch { /* A blocked user is skipped without stopping the broadcast. */ } } session.adminStep = undefined; await ctx.reply(`Broadcast sent to ${sent} recipient${sent === 1 ? "" : "s"}.`); return; }
  } catch (error) { await ctx.reply(error instanceof LibraryUnavailableError ? "The library is getting ready. Please try again shortly." : "Couldn't save that change. Please try again."); }
});
export default composer;
